### ISSUE TITLE
Título y breve descripción del TFG 

### ISSUE THREAD

**Issue by ajcanepa** [rocioagmi/TFG#3]
Hola @rocioagmi ,

Ahora que ya tenemos en vista las BBDD con las que puedes trabajar, con independencia de cuál sea finalmente la elegida, sí que estaría bien que enviśemos el documento que nos pide José Francisco.

Te pido, por favor, que redactes un título y una breve descripción y nosotros con @SoniaRamosGomez le damos una vuelta y la enviamos.

Un saludo y ¡gracias!

**Comment by ajcanepa** [comment]
> Hola @ajcanepa @SoniaRamosGomez , Un posible título junto con una breve descripción para el TFG, teniendo en cuenta que sabemos que vamos a analizar el microbioma tanto de personas sanas como de personas con la enfermedad, pero no tenemos claro todavía el punto extra que le vamos a dar, se me ocurre algo mas bien general, que podría ser: "_El papel de la microbiota intestinal en la esclerosis múltiple_". Este trabajo se va a centrar en explorar la relación entre la esclerosis múltiple y la microbiota intestinal humana. Mediante la revisión de la literatura existente y el análisis de datos metagenómicos, tanto de personas sanas como de aquellas que padecen la enfermedad, y su revisión para la búsqueda de nuevos puntos de partida a través de los cuales se pueda mejorar la comprensión de su funcionamiento, y la forma en que se ve afectada por la microbiota intestinal y su manejo.

Hola @rocioagmi ,
No me desagrada, pero te preguntaría ¿Qué aporte a la ingeniería conlleva este título/descripción? Desde un punto de vista sólo de salud (o solo biológico) no está mal, pero recuerda que en un grado como el que cursas, has de incorporar el componente tecnológico de alguna manera.

Recuerdo que al comienzo, habíamos hablado con @SoniaRamosGomez de que pudieras establecer un protocolo con un flujo de trabajo (workflow/Pipeline). 

Ideas como estas hay muchas, pero te dejo una que se llama [TORMES](https://github.com/nmquijada/tormes) que está bastante bien. Puedes ver el readme de su repositorio un esquema que además de tener que desarrollarlo tu para tu TFG, verás como sirve tener claro el conjunto de pasos/herramientas que te permiten desarrollar la idea (sea un pipeline o no).

En resumen, **necesitas un componente "tecnológico"** que puede ser el desarrollo de un pipeline para un ejercicio en concreto, por el ejemplo el del "*rol de la microbiota intestinal en la esclerosis múltiple*".

Dale una vuelta y lo vamos hablando....

**Comment by SoniaRamosGomez** [comment]
Hola @rocioagmi (y @ajcanepa ),
Creo que es demasiado ambiguo, quizas podemos perfilar empleando términos como análisis o caracterización del microbioma en la esclerosis múltiple. Como bien dice @ajcanepa hay que dar el punto de vista de la Ingeniería y, en este caso, va a pasar por el uso (o desarrollo y uso) de un pipeline que nos permita caracterizar (profiling) mediante anotación (funcional o taxonómico) de las muestas. Este tipo de análisis son básicos en cualquier estudio de metagenómica y puede ayudar a dar un título más específico sin ser excesivamente concretos.

Vamos hablando

**Comment by rocioagmi** [comment]
Hola @SoniaRamosGomez @ajcanepa,
Le he dado al título una vuelta y la descripción también la he cambiado un poco:

"Desarrollo de un pipeline para la caracterización del microbioma intestinal en la esclerosis múltiple."

Este trabajo se va a centrar en la implementación de un pipeline para explorar la relación entre la microbiota intestinal y la esclerosis múltiple. Mediante la revisión de la literatura existente, y a través de aplicar herramientas de análisis metagenómico a los datos de la microbiota intestinal, tanto de controles sanos, como de personas que padecen la enfermedad. Caracterizar mediante anotación los microorganismos presentes en el intestino de personas que presentan esta enfermedad, con el fin de abrir nuevas vías de investigación y estrategias terapéuticas.  

Un saludo

**Comment by ajcanepa** [comment]
> Hola @SoniaRamosGomez @ajcanepa, Le he dado al título una vuelta y la descripción también la he cambiado un poco:
> 
> "Desarrollo de un pipeline para la caracterización del microbioma intestinal en la esclerosis múltiple."
> 
> Este trabajo se va a centrar en la implementación de un pipeline para explorar la relación entre la microbiota intestinal y la esclerosis múltiple. Mediante la revisión de la literatura existente, y a través de aplicar herramientas de análisis metagenómico a los datos de la microbiota intestinal, tanto de controles sanos, como de personas que padecen la enfermedad. Caracterizar mediante anotación los microorganismos presentes en el intestino de personas que presentan esta enfermedad, con el fin de abrir nuevas vías de investigación y estrategias terapéuticas.
> 
> Un saludo

Gracias @rocioagmi . 

Si a @SoniaRamosGomez le parece bien, yo agrego aquí unas (muy breves) modificaciones, casi semánticas y con su visto bueno, se lo enviamos a José Francisco.

Mi propuesta de título es (usaré _cursivas para mostrar mis cambios_)

"Desarrollo de un pipeline para la _automatización_ y caracterización del microbioma intestinal en la esclerosis múltiple."

Mi propuesta de desarrollo es (usaré _cursivas para mostrar mis cambios_)

Este trabajo se va a centrar en la implementación de un pipeline para _automatizar los procesos de consulta y carga de bases de datos disponibles_, _entregar herramientas para_  explorar _y analizar_ la relación entre la microbiota intestinal y la esclerosis múltiple. Mediante la revisión de la literatura existente, y a través de aplicar herramientas de análisis metagenómico a los datos de la microbiota intestinal, tanto de controles sanos, como de personas que padecen la enfermedad. Caracterizar mediante anotación los microorganismos presentes en el intestino de personas que presentan esta enfermedad, con el fin de abrir nuevas vías de investigación y estrategias terapéuticas. _Se revisarán y propondrán herramientas tanto de análisis como de visualización de los resultados para favorecer el uso futuro de la herramienta para esta y otras temáticas similares_.

**Comment by SoniaRamosGomez** [comment]
Buenos días @rocioagmi ,
A mi me gusta un poco más con las adaptaciones de @ajcanepa . Voy a incluir dos pequeños cambios que he marcado en negrita para que los podáis ver:

*"Desarrollo de un pipeline para la automatización y caracterización del microbioma intestinal en la esclerosis múltiple"*
Este trabajo se va a centrar en la implementación de un pipeline para automatizar los procesos de consulta y carga de bases de datos disponibles, entregar herramientas para explorar y analizar la relación entre la microbiota intestinal y la esclerosis múltiple. Mediante la revisión de la literatura existente, y a través de aplicar herramientas de análisis metagenómico a los datos de la microbiota intestinal, tanto de controles sanos, como de **personas diagnósticadas de esclerosis múltiple**. Caracterizar **diferencialmente** mediante anotación los microorganismos presentes en el intestino de **pacientes frente a individuos sanos**, con el fin de abrir nuevas vías de investigación y estrategias terapéuticas. Se revisarán y propondrán herramientas tanto de análisis como de visualización de los resultados para favorecer el uso futuro de la herramienta para esta y otras temáticas similares.

Si lo veis bien, lo enviamos ya al Coordinador de los TFG y damos por cerrada esta issue.

**Comment by ajcanepa** [comment]
De acuerdo,

Por mi parte está OK y con esto lo damos por cerrado.

Muchas gracias @SoniaRamosGomez y @rocioagmi
