### ISSUE TITLE
Actualizar RStudio

### ISSUE THREAD

**Issue by rocioagmi** [rocioagmi/TFG#4]
Necesitamos actualizar R y RStudio a la última versión disponible. Además, instalar en la versión más actual los paquetes que vayamos a necesitar. Así, evitaremos problemas con las versiones.

**Comment by rocioagmi** [comment]
Hola @ajcanepa @SoniaRamosGomez,
Tengo ya actualizados tanto R, como RStudio y he instalado ya varios paquetes incluido Bioconductor. También he revisado que los paquetes que ya tenía instalados estén actualizados. Solo me queda conseguir "unir" bien del todo el proyecto en RStudio con el repositorio de github.

**Comment by ajcanepa** [comment]
> Hola @ajcanepa @SoniaRamosGomez, Tengo ya actualizados tanto R, como RStudio y he instalado ya varios paquetes incluido Bioconductor. También he revisado que los paquetes que ya tenía instalados estén actualizados. Solo me queda conseguir "unir" bien del todo el proyecto en RStudio con el repositorio de github.

De acuerdo Rocío,
He actualizado el repositorio de prácticas porque aunque lo explico, los estudiantes de fuentes siempre olvidan esto del repositorio.
Existe ahora una subsección [Control de Versiones (R/RStudio and Git/Github)](https://github.com/ajcanepa/PRACTICA_TEMA5/tree/main?tab=readme-ov-file#control-de-versiones-rrstudio-and-gitgithub), en la que entrego varios enlaces a cómo enganchar RStudio con el Repositorio de GitHub (los primeros los mejores).

Seguro que te vienen bien, sino me avisas y te pasas por el despacho un momento, que esto es sencillo!
Suerte!
