### ISSUE TITLE
Descarga de los datos de la BBDD 

### ISSUE THREAD

**Issue by rocioagmi** [rocioagmi/TFG#5]
Probar a descargar todas las muestras fastq de la BBDD que hemos seleccionado.

**Comment by rocioagmi** [comment]
Hola @ajcanepa, @SoniaRamosGomez,
Ya tengo descargadas todas las secuencias. Son 65 muestras y en cada una tenemos dos secuencias, supongo que una por cada hebra del ADN, en total 130. Todas ellas identificadas por si es paciente sano o con esclerosis múltiple y por si es la lectura 1 o 2 dentro de cada muestra.

**Comment by ajcanepa** [comment]
> Hola @ajcanepa, @SoniaRamosGomez, Ya tengo descargadas todas las secuencias. Son 65 muestras y en cada una tenemos dos secuencias, supongo que una por cada hebra del ADN, en total 130. Todas ellas identificadas por si es paciente sano o con esclerosis múltiple y por si es la lectura 1 o 2 dentro de cada muestra.

Hola Rocío, 
De cara al **pipeline** tengo una pregunta (_este tema no lo uso con el detalle que me gustaría y de ahí mi duda_), ¿podrías **automatizar** tanto el proceso de **descarga** (si te conectas a una API o si usas un paquete para las bases de datos que estás usando), como el de **almacenamiento** (entiendo que al ser datos semi-estructurados podrías guardar la información en un fichero .json o en una base de datos **no-SQL** local como [MongoDB](https://www.mongodb.com/) y el paquete de R [Mongolite](https://cran.r-project.org/web/packages/mongolite/index.html)) para tu TFG? Hay un Manual de Usuario bastante bueno [Mongolite User Manual](https://jeroen.github.io/mongolite/), donde precisamente tiene un capítulo para crear la base de datos usando ficheros .json [Chapter 5 Import / Export](https://jeroen.github.io/mongolite/import-export.html#json)

Todas estas automatizaciones y desarrollos son muy buenos para el TFG....me avisas cualquier cosa.

**Comment by rocioagmi** [comment]
Hola @ajcanepa , 
Respecto a la automatización me parece un punto muy interesante y mientras lo he estado intentando implementar me han surgido algunos problemas, primero tuve que crearme otra sesión en mi portátil donde usar RStudio para que la dirección del directorio de trabajo no tuviese tildes, ya que mi usuario lleva una. 
Luego a la hora de usar la función del paquete R Mongolite tengo el problema de que tengo dos enlaces por muestra (una para cada hebra) para descargar la información. Mi idea era, descargarme el script tsv, en el que aparece tal cual la tabla que vemos al entrar en la base de datos, e ir recorriendo en bucle la columna donde se encuentran los 2 enlaces de descarga para cada muestra, separarlos y aplicarles la función de Mongolite para poder importarlos. 
Otro problema que se me presenta es que al no usar Rstudio en la cuenta del administrador del portátil, no lo interpreta como un tsv y se me guarda como un txt, entonces no tengo forma de acceder a los enlaces como filas de una columna.

Siento la tardanza de mi respuesta.
Muchas gracias de antemano.

**Comment by SoniaRamosGomez** [comment]
Buenos días @rocioagmi ,
Obviamente sería muy útil tener un sistema de descarga de los datos. Nos interesan fundamentalemente los datos en formato fasta (fastq.gz) y, para que sean más fiables, debería haber dos ficheros por cada muestra (Sample Accession). Normalmente vienen codificados con el mismo nombre de la "Run Acession" y _1 para la hebra forward, _2 para la hebra reverse.
Necesitamos ambas hebras para el análisis, esto nos permite comprobar si hay regiones a eliminar o coberturas.

No sé si he ayudado.

**Comment by ajcanepa** [comment]
[like]  ANTONIO JESUS CANEPA ONETO reacted to your message:
________________________________

**Comment by rocioagmi** [comment]
Buenos días @SoniaRamosGomez y @ajcanepa,
Sí, muchas gracias. Entiendo lo que me decís acerca de la automatización de la descarga de los datos y la necesidad de tener los dos archivos fasta.gz por cada muestra. He estado buscando API y paquetes R que nos sirvan para la descarga de los datos directamente desde el ENA. Encontré un paquete de R en github [RENA](https://natesheehan.github.io/rena/) pero no sé cómo de fiable es, he entendido que permite descargar archivos del ENA a través del número de acceso al estudio o las secuencias. También encontré una API para la descarga de archivos tanto del ENA como del SRA del NCBI pero era para bioconda.
Así que por el momento voy a intentarlo con el paquete R que he encontrado a ver si con eso puedo dejar cerrada esta parte.  
Muchas gracias

**Comment by ajcanepa** [comment]
> Buenos días @SoniaRamosGomez y @ajcanepa, Sí, muchas gracias. Entiendo lo que me decís acerca de la automatización de la descarga de los datos y la necesidad de tener los dos archivos fasta.gz por cada muestra. He estado buscando API y paquetes R que nos sirvan para la descarga de los datos directamente desde el ENA. Encontré un paquete de R en github [RENA](https://natesheehan.github.io/rena/) pero no estoy consiguiendo instalarlo, he entendido que permite descargar archivos del ENA a través del número de acceso al estudio o las secuencias. También encontré una API para la descarga de archivos tanto del ENA como del SRA del NCBI [fastq-dl](https://github.com/rpetit3/fastq-dl), no está diseñada para R pero podemos usarla para obtener los datos y luego ya usarlos dentro de R. Por último he encontrado he encontrado una [guía del ENA](https://ena-docs.readthedocs.io/en/latest/retrieval/file-download.html) sobre cómo descargar archivos de datos pero no entiendo bien cómo podría integrarla en el código en R,. Así que por el momento voy a seguir investigando si hay más opciones. Muchas gracias

Hola @rocioagmi , buenas.
Estoy corto de tiempo ahora mismo, entonces te responderé a __modo general__. Está estupendo que uses paquetes que tengan implementadas ciertas funcionalidades (descarga, visualización, etc.); pero claramente no todo lo que necesitas estará implementado.

Además como futura Ingeniera de la salud, crear tus propias herramientas es "_lo suyo_". Si miras/lees en las mismas páginas que nos has enviado, te muestran como descargar los datos usando un comando bash llamado `wget`. [https://ena-docs.readthedocs.io/en/latest/retrieval/file-download.html#using-wget](https://ena-docs.readthedocs.io/en/latest/retrieval/file-download.html#using-wget).

Este mismo comando lo puedes "_emular_" con la función base de R `download.file`, de tal manera que con el código que te paso ahora podrías hacer la descarga:

```
# Especifica la URL del archivo .fastq.gz en ENA
url <- "ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR164/ERR164407/ERR164407.fastq.gz"

# Especifica el nombre del archivo de destino
destfile <- "ERR164407.fastq.gz"

# Descarga el archivo
download.file(url, destfile, mode = "wb")
```

Entonces, no siempre estará la función que necesitas, pero a partir de este código puedes crear tú misma una función que pasándole a el objeto `url` una lista de archivos ".fastq.gz", a través de un for loop te los descargue todos.....

¿me explico?

**Comment by SoniaRamosGomez** [comment]
Buenos días @rocioagmi y @ajcanepa ,
Creo que en esto no puedo ayudar pero, si @ajcanepa puede atenderte yo intentaré acudir por si puedo ayudar en algún aspecto.

**Comment by rocioagmi** [comment]
Buenos días @ajcanepa y @SoniaRamosGomez ,
Como tal la implementación de la descarga automatizada de los datos la tengo hecha, el problema que estoy teniendo es conseguir que se me suban los cambios a GitHub. De forma resumida, lo que he hecho es que el usuario, una vez ya sabe qué datos de qué estudio quiere descargarse dentro del ENA, se descargue el informe que aparece junto a los datos.
A continuación, al ejecutarse el código te pide que introduzcas la dirección donde tienes descargado el informe en el ordenador y a partir de ahí, R lee el informe y extrae los enlaces para descargar las muestras y las descarga.
Es una forma de hacerlo, pero sólo funciona para la base de datos del ENA.
Un saludo

**Comment by ajcanepa** [comment]
De acuerdo @rocioagmi.
En principio me parece bien que esté automatizado, quizás hoy cuando nos juntemos y veamos el problema de los cambios en Github te pregunto un par de cosas, más pero en principio este es el tipo de desarrollo (ojo que no será el único) que desde la informática puedes aportar en tu TFG.
Que sirva para solo una base de datos (ENA en este caso), no lo veo como un problema si vamos a desarrollar más cosas dentro de los datos que ofrece ENA. Es más, quizás en la sección del TFG de líneas futuras, se puede poner la implementación de esta función para oitras BBDD de tal manera que luego de la descarga se "__conecten__" con tu *pipeline* y sea útil, igual @SoniaRamosGomez nos puede comentar algo más, pero de momento (yo) no lo veo  prioritario.
Nos vemos!

**Comment by rocioagmi** [comment]
Hola @ajcanepa y @SoniaRamosGomez,
El código correspondiente a esta issue esta creado y funciona correctamente. En concreto he creado una función que a partir del número de acceso al proyecto ENA descargue los datos. Con ello dejo cerrada esta issue.
Un saludo
